# Generated by Django 5.1.7 on 2025-03-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voiture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marque", models.CharField(max_length=100)),
                ("modele", models.CharField(max_length=100)),
                ("annee", models.IntegerField()),
                ("kilometrage", models.IntegerField()),
                (
                    "prix_vente",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "prix_location_jour",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField()),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("vendu", "Vendu"),
                            ("loué", "Loué"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                (
                    "type_offre",
                    models.CharField(
                        choices=[
                            ("vente", "À vendre"),
                            ("location", "À louer"),
                            ("les_deux", "À vendre et à louer"),
                        ],
                        default="vente",
                        max_length=20,
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
