# Generated by Django 5.1.7 on 2025-03-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventelocavoiture", "0002_imagevoiture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("F", "Feminin"), ("M", "Masculin")], max_length=1
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
