# Generated by Django 5.1.7 on 2025-03-14 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventelocavoiture", "0004_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "type_transaction",
                    models.CharField(
                        choices=[("achat", "Achat"), ("location", "Location")],
                        max_length=10,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_debut_location", models.DateField(blank=True, null=True)),
                ("date_fin_location", models.DateField(blank=True, null=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventelocavoiture.utilisateur",
                    ),
                ),
                (
                    "voiture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventelocavoiture.voiture",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Manager",
        ),
    ]
