# Generated by Django 5.1.7 on 2025-03-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventelocavoiture", "0005_transaction_delete_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="numeros",
            field=models.IntegerField(null=True),
        ),
    ]
