# Generated by Django 5.1.7 on 2025-03-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventelocavoiture", "0010_alter_utilisateur_numeros"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="numeros",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
